spring.application.name=splitwise
spring.datasource.url=jdbc:mysql://localhost:3306/splitwise_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1908

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anshu.pall2004@gmail.com
spring.mail.password=Aditya@pal67
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=bdjewdfuwehdi344ry74987329uekl23qneoi12y389123912euqkjedn
jwt.expiration=86400000
